# Generated by Django 3.0.4 on 2020-03-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Work',
        ),
    ]
