# Generated by Django 3.0.4 on 2020-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_auto_20200331_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='img',
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='media/uploads/visit', verbose_name='Ссылка картинки'),
        ),
    ]
