# Generated by Django 3.0.4 on 2020-04-10 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20200401_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
    ]
